spring.application.name=libreriacultural
server.port=8083

spring.datasource.url=jdbc:mysql://localhost:3306/culture_tracker
spring.datasource.username=root
spring.datasource.password=1234
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# --- HikariCP Connection Pool Settings to Prevent Connection Reset / Timeouts ---
spring.datasource.hikari.connection-test-query=SELECT 1
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.max-lifetime=1800000

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

omdb.api.key=thewdb

# --- Max Upload Sizes ---
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
server.tomcat.max-http-post-size=10MB
server.tomcat.max-swallow-size=10MB
spring.thymeleaf.cache=false  
google.books.api.key=AIzaSyADfHNGywrcyfq2r-2uKwCT8bpgiNW7QSc